### ISSUE TITLE
AttributeError: 'str' object has no attribute 'query_str' | [BUG]

### ISSUE THREAD

**Issue by vanshgupta7** [truera/trulens#937]
**Bug Description**
#916  Continuing on this issue.
Still facing the same error.

**Relevant Logs/Tracebacks**
```
2024-02-26 11:12:57.113 Uncaught app exception
Traceback (most recent call last):
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "D:\Evaluation Framework\Rohit's_code\main.py", line 98, in <module>
    response = tru_lens_eval(index=index, user_prompt=prompt)
  File "D:\Evaluation Framework\Rohit's_code\tru.py", line 58, in tru_lens_eval
    with tru_query_engine_recorder as recording:
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\app.py", line 910, in __exit__
    raise exc_value
  File "D:\Evaluation Framework\Rohit's_code\tru.py", line 59, in tru_lens_eval
    llm_response = query_engine.query(str_or_query_bundle=user_prompt)
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\instruments.py", line 744, in tru_wrapper
    handle_done(rets=rets)
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\instruments.py", line 706, in handle_done
    records[ctx] = ctx.app.on_add_record(
    record = ctx.finish_record(
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\app.py", line 413, in finish_record
    record = calls_to_record(
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\app.py", line 954, in build_record
    main_in = self.main_input(func, sig, bindings)
  File "D:\Evaluation Framework\Rohit's_code\.venv\lib\site-packages\trulens_eval\tru_llama.py", line 301, in main_input
    return str_or_bundle.query_str
AttributeError: 'str' object has no attribute 'query_str'
```

**Environment:**
```
`llama-index==0.10.12

trulens-eval @ git+https://github.com/truera/trulens@979295beb8d1121fb334abe88445d3c8ef3f7700#subdirectory=trulens_eval.
Did try latest version 0.24.1 as well`
```

**Additional context**
It was working well with llama_index version 0.9.46 and trulens verson 0.22.2

**Comment by joshreini1** [comment]
Hey @vanshgupta7 - do you have a contained example you can share?

**Comment by vanshgupta7** [comment]
It was a HuggingFace API error.. it got resolved... sorry for the trouble
