### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by muexxl** [truera/trulens#670]
the python import crashes based on the version of llama-index

works fine with llama-index 0.9.8
crashes with llama-index 0.9.14 

Mac OS 14.2
Python 3.11.5
trulens-eval                0.18.3

workaround: roll back llama-index to 0.9.8
`pip install llama-index==0.9.8`

Please find below the complete ImportError:
```
{
	"name": "ImportError",
	"message": "cannot import name 'LLM' from 'llama_index.llms.base' (/Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/llama_index/llms/base.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[8], line 1
----> 1 from trulens_eval import Tru

File ~/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py:97
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=94'>95</a> from trulens_eval.tru_custom_app import instrument
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=95'>96</a> from trulens_eval.tru_custom_app import TruCustomApp
---> <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=96'>97</a> from trulens_eval.tru_llama import TruLlama
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=97'>98</a> from trulens_eval.utils.threading import TP
    <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=99'>100</a> __all__ = [
    <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=100'>101</a>     'Tru',
    <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=101'>102</a>     'TruBasicApp',
   (...)
    <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=114'>115</a>     'TP'
    <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/__init__.py?line=115'>116</a> ]

File ~/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py:44
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py?line=40'>41</a> from llama_index.schema import BaseComponent
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py?line=42'>43</a> # LLMs
---> <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py?line=43'>44</a> from llama_index.llms.base import LLM  # subtype of BaseComponent
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py?line=45'>46</a> # misc
     <a href='file:///Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/trulens_eval/tru_llama.py?line=46'>47</a> from llama_index.indices.query.base import BaseQueryEngine

ImportError: cannot import name 'LLM' from 'llama_index.llms.base' (/Users/stephan/LLM_Workshop/venv/lib/python3.11/site-packages/llama_index/llms/base.py)"
}
```
´´´

**Comment by joshreini1** [comment]
Following up @muexxl - this change is released! Please upgrade to trulens_eval==0.19.1. Thanks!
